remove unused latestapps.dat code
latestapps.dat was being used for the old-website, it's not used anymore

Fixes the following crash in production:
```
2020-09-13 19:26:59,000 CRITICAL: Unknown exception found!
Traceback (most recent call last):
  File "/home/fbuild/fdroidserver/fdroid", line 22, in <module>
    fdroidserver.__main__.main()
  File "/home/fbuild/fdroidserver/fdroidserver/__main__.py", line 230,
in main
    raise e
  File "/home/fbuild/fdroidserver/fdroidserver/__main__.py", line 211,
in main
    mod.main()
  File "/home/fbuild/fdroidserver/fdroidserver/update.py", line 2451, in
main
    app = apps[appid]
KeyError: '45b464b398a7d9fac5a186bd3d3d8dc1e6a25f7f9cd48c7462619b1e5fba87c2'
```