nightly: print error if env var is missing
This should help with debugging a lot. Before this, it showed an obtuse
stacktrace when an env var was not set:

```
Traceback (most recent call last):
  File "/usr/bin/fdroid", line 33, in <module>
    sys.exit(load_entry_point('fdroidserver==2.4.0', 'console_scripts', 'fdroid')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/fdroidserver/__main__.py", line 222, in main
    raise e
  File "/usr/lib/python3/dist-packages/fdroidserver/__main__.py", line 203, in main
    mod.main()
  File "/usr/lib/python3/dist-packages/fdroidserver/nightly.py", line 352, in main
    writer.set_value('user', 'name', git_user_name)
  File "/usr/lib/python3/dist-packages/git/config.py", line 122, in assure_data_present
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/git/config.py", line 134, in flush_changes
    rval = non_const_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/git/config.py", line 855, in set_value
    self.set(section, option, self._value_to_string(value))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/git/config.py", line 838, in _value_to_string
    return force_text(value)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gitdb/utils/encoding.py", line 18, in force_text
    return str(data, encoding)
           ^^^^^^^^^^^^^^^^^^^
TypeError: decoding to str: need a bytes-like object, NoneType found
```