switch test_signatures.py to mkdtemp to fix mystery
I have no idea what is causing this to fail, but the mkdtemp pattern used
in other test files seems to fix it.

https://gitlab.com/fdroid/fdroidserver/-/jobs/11776468083
======================================================================
ERROR: test_main (tests.test_signatures.SignaturesTest.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/fdroid/fdroidserver/tests/test_signatures.py", line 28, in test_main
    with TemporaryDirectory() as tmpdir, TmpCwd(tmpdir):
                                         ^^^^^^^^^^^^^^
  File "/builds/fdroid/fdroidserver/tests/shared_test_code.py", line 44, in __enter__
    self.orig_cwd = os.getcwd()
                    ^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
----------------------------------------------------------------------