zlib-ng's non-determinism breaks implanting APK sigs #1354
Python 3.14 defaults to building with zlib-ng, so this is a workaround
until signature copying is fixed.

This also fixes !1848 tests on macOS:
https://gitlab.com/fdroid/fdroidserver/-/jobs/15472305534
FileNotFoundError: [Errno 2] No such file or directory: '/etc/os-release'